image: Visual Studio 2017
branches:
  only:
    - master
    - develop
    - /features\/.+/
environment:
  # No need to pre-warm the `NuGet` cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - LICENSE
    - README.md
    - .circleci/*
assembly_info:
    # We'll version the binaries and the NuGet package in the build script
    patch: false                      
install:
  - ps: dotnet tool install -g Cake.Tool --version 0.34.1
  - ps: dotnet tool install -g coveralls.net --version 1.0.0
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet cake build.cake --bootstrap
  - ps: dotnet cake build.cake --pack
after_build:
  - ps: csmacnz.coveralls --opencover -i coverage\coverage.opencover.xml --useRelativePaths
test: off
artifacts:
  - path: artifacts\*.nupkg
    name: NuGet Packages
  - path: artifacts\*.snupkg
    name: NuGet Symbol Packages
deploy:
- provider: NuGet
  api_key:
    secure: RffBv1JUPzoM/xvk4z0YoMh67V7jU2WBvI8RYEl5m3nOQoX1aoJ8UbJ4S4K+jWlS
  on:
    # release from master branch only
    branch: master       